'use strict';

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const state = { app: null, settings: null, meta: null, analyzedUrl: '', jobs: new Map(), browser: null, diag: '' };
const pages = {
  download: ['MEDIA DOWNLOAD', 'Завантаження'], browser: ['BROWSER SESSION', 'Вбудований браузер'],
  queue: ['ACTIVE WORK', 'Черга'], history: ['LOCAL ARCHIVE', 'Історія'], settings: ['SYSTEM', 'Налаштування']
};
const statusText = { queued:'У черзі', starting:'Старт', downloading:'Завантаження', processing:'Обробка', cancelling:'Скасування', completed:'Готово', failed:'Помилка', cancelled:'Скасовано' };
let toastTimer;
function toast(text,error=false){const el=$('#toast');if(!el)return;el.textContent=String(text||'');el.classList.toggle('error',error);el.classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.add('hidden'),3800)}
function message(text='',error=false){const el=$('#messageBox');if(!el)return;el.textContent=text;el.classList.toggle('error',error);el.classList.toggle('hidden',!text)}
function busy(btn,on,label='Зачекайте…'){if(!btn)return;if(!btn.dataset.label)btn.dataset.label=btn.textContent;btn.disabled=on;btn.textContent=on?label:btn.dataset.label}
function fmtDuration(v){const n=Math.max(0,Number(v)||0),h=Math.floor(n/3600),m=Math.floor(n%3600/60),s=Math.floor(n%60);return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function fmtDate(v){try{return new Date(v).toLocaleString('uk-UA')}catch{return ''}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function auth(){const mode=$('input[name="authMode"]:checked')?.value||'none';return{authMode:mode,cookiesFile:mode==='file'?($('#cookiesInput')?.value||''):''}}
function authLabel(m=auth().authMode){return m==='browser'?'Browser session':m==='file'?'cookies.txt':'Без cookies'}
function options(){return{url:$('#urlInput').value.trim(),outputDirectory:$('#outputInput').value,preset:$('#presetSelect').value,includePlaylist:$('#playlistCheck').checked,writeThumbnail:$('#thumbnailCheck').checked,embedMetadata:$('#metadataCheck').checked,downloadSubtitles:$('#subtitlesCheck').checked,autoSubtitles:$('#autoSubtitlesCheck').checked,subtitleLanguages:$('#subtitleLanguagesInput').value.trim()||'uk,en',...auth()}}
function switchPage(name){$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===name));$$('.page').forEach(x=>x.classList.toggle('active',x.id===`page-${name}`));const[e,t]=pages[name]||pages.download;$('#pageEyebrow').textContent=e;$('#pageTitle').textContent=t;if(name==='history')renderHistory();if(name==='browser'||name==='settings')refreshBrowser();if(name==='settings')refreshBinaries()}
async function persist(){if(!state.settings)return;state.settings=await window.astra.settings.set({outputDirectory:$('#outputInput').value,preset:$('#presetSelect').value,concurrentDownloads:Number($('#concurrencySelect').value),writeThumbnail:$('#thumbnailCheck').checked,embedMetadata:$('#metadataCheck').checked,downloadSubtitles:$('#subtitlesCheck').checked,autoSubtitles:$('#autoSubtitlesCheck').checked,subtitleLanguages:$('#subtitleLanguagesInput').value.trim()||'uk,en',...auth()})}
function applySettings(s){state.settings=s;$('#outputInput').value=s.outputDirectory||'';$('#presetSelect').value=s.preset||'mp4-1080';$('#concurrencySelect').value=String(s.concurrentDownloads||2);$('#thumbnailCheck').checked=!!s.writeThumbnail;$('#metadataCheck').checked=s.embedMetadata!==false;$('#subtitlesCheck').checked=!!s.downloadSubtitles;$('#autoSubtitlesCheck').checked=!!s.autoSubtitles;$('#subtitleLanguagesInput').value=s.subtitleLanguages||'uk,en';$('#cookiesInput').value=s.cookiesFile||'';const r=$(`input[name="authMode"][value="${s.authMode||'none'}"]`)||$('input[name="authMode"][value="none"]');r.checked=true;updateAuthUI()}
function updateAuthUI(){const m=auth().authMode;$$('.auth-option').forEach(x=>x.classList.toggle('active',x.dataset.mode===m));$('#browserAuthPanel').classList.toggle('hidden',m!=='browser');$('#fileAuthPanel').classList.toggle('hidden',m!=='file');$('#authStatusMini').textContent=authLabel(m);$('#authHeaderBadge').innerHTML=`<span></span>${authLabel(m)}`;$('#browserModeLabel').textContent=m==='browser'?'Активний':m==='none'?'Не використовується':'cookies.txt';$('#downloadSummary').textContent=`${$('#presetSelect').selectedOptions[0]?.textContent||''} · ${authLabel(m)}`;persist().catch(()=>{});if(m==='browser')refreshBrowser()}
async function analyze(){const url=$('#urlInput').value.trim();if(!url)return message('Вставте посилання на відео.',true);const b=$('#analyzeButton');busy(b,true,'Аналіз…');message('Перевіряю посилання та доступні формати…');try{const m=await window.astra.video.analyze(url,auth());state.meta=m;state.analyzedUrl=url;$('#videoTitle').textContent=m.title||'Без назви';$('#videoUploader').textContent=m.uploader||'Автор не вказаний';$('#durationBadge').textContent=fmtDuration(m.duration);$('#extractorBadge').textContent=(m.extractor||'VIDEO').toUpperCase();const chips=[m.formatCount?`${m.formatCount} форматів`:'',m.subtitles?.length?`${m.subtitles.length} мов субтитрів`:'',m.availability||''].filter(Boolean);$('#metaChips').innerHTML=chips.map(x=>`<span>${esc(x)}</span>`).join('');const img=$('#thumbnailImage');img.removeAttribute('src');if(m.thumbnail){try{img.src=await window.astra.video.thumbnail(m.thumbnail)}catch{}}$('#previewCard').classList.remove('hidden');message(`Посилання проаналізовано. Режим: ${authLabel()}.`)}catch(e){state.meta=null;state.analyzedUrl='';$('#previewCard').classList.add('hidden');message(e.message,true)}finally{busy(b,false)}}
async function addDownload(){const o=options();if(!o.url)return message('Вставте посилання.',true);if(!o.outputDirectory)return message('Оберіть папку збереження.',true);const b=$('#downloadButton');busy(b,true,'Додаю…');try{const j=await window.astra.downloads.add(o,state.analyzedUrl===o.url?state.meta:null);state.jobs.set(j.id,j);renderQueue();await persist();toast('Завдання додано в чергу');switchPage('queue')}catch(e){message(e.message,true)}finally{busy(b,false)}}
function renderQueue(){const list=$('#queueList'),jobs=[...state.jobs.values()].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));const active=jobs.filter(j=>!['completed','failed','cancelled'].includes(j.status)).length;$('#queueCount').textContent=active;$('#queuePageCount').textContent=active;if(!jobs.length){list.innerHTML='<div class="empty-state">Черга порожня</div>';return}list.innerHTML=jobs.map(j=>{const done=['completed','failed','cancelled'].includes(j.status);return `<article class="job card" data-id="${esc(j.id)}"><div class="job-main"><div class="job-title-row"><div><h3>${esc(j.title||j.url)}</h3><p class="muted">${esc([j.uploader,j.preset,j.stage].filter(Boolean).join(' · '))}</p></div><span class="status-badge ${esc(j.status)}">${statusText[j.status]||esc(j.status)}</span></div><div class="progress-track"><div class="progress-fill" style="width:${Math.max(0,Math.min(100,Number(j.progress)||0))}%"></div></div><div class="job-stats"><span>${Math.round(Number(j.progress)||0)}%</span><span>${esc(j.speed||'')}</span><span>${j.eta?`ETA ${esc(j.eta)}`:''}</span></div>${j.errorMessage?`<pre class="job-error">${esc(j.errorCode||'ERROR')}\n${esc(j.errorMessage)}</pre>`:''}</div><div class="job-actions">${j.status==='completed'?'<button class="button secondary" data-action="open">Відкрити</button>':''}${['failed','cancelled'].includes(j.status)?'<button class="button secondary" data-action="retry">Повторити</button>':''}${!done?'<button class="button danger-ghost" data-action="cancel">Скасувати</button>':''}</div></article>`}).join('')}
async function queueAction(e){const btn=e.target.closest('[data-action]'),row=e.target.closest('.job');if(!btn||!row)return;const id=row.dataset.id,j=state.jobs.get(id);try{if(btn.dataset.action==='cancel')await window.astra.downloads.cancel(id);if(btn.dataset.action==='retry'){const n=await window.astra.downloads.retry(id);state.jobs.set(n.id,n)}if(btn.dataset.action==='open')await window.astra.system.openPath(j.outputPath||j.outputDirectory);renderQueue()}catch(err){toast(err.message,true)}}
async function renderHistory(){const box=$('#historyList');try{const rows=await window.astra.history.list(200);if(!rows.length){box.innerHTML='<div class="empty-state">Історія порожня</div>';return}box.innerHTML=rows.map(x=>`<div class="history-item"><div><h3>${esc(x.title||x.url)}</h3><p class="muted">${esc([x.uploader,x.preset,fmtDate(x.completedAt)].filter(Boolean).join(' · '))}</p></div><button class="button secondary" data-path="${esc(x.outputPath||'')}">Відкрити</button></div>`).join('')}catch(e){box.innerHTML=`<div class="empty-state">${esc(e.message)}</div>`}}
async function refreshBrowser(){try{const s=await window.astra.browser.status();state.browser=s;$('#browserCookieCount').textContent=s.cookieCount;$('#browserDomainCount').textContent=s.domainCount;$('#browserDot').classList.toggle('online',s.hasSession);$('#browserSessionText').textContent=s.hasSession?`${s.cookieCount} cookies у ${s.domainCount} доменах`:'Сесія порожня — авторизуйтеся у браузері';$('#settingsBrowserStatus').textContent=s.hasSession?`${s.cookieCount} cookies, ${s.domainCount} доменів`:'Сесія порожня';$('#browserDomains').innerHTML=s.domains?.length?s.domains.map(d=>`<span>${esc(d)}</span>`).join(''):'<span class="empty-inline">Авторизованих доменів поки немає</span>'}catch(e){$('#browserSessionText').textContent=e.message}}
async function clearBrowser(){if(!confirm('Очистити всі cookies та авторизації AstraFetch Browser?'))return;try{await window.astra.browser.clear();await refreshBrowser();toast('Сесію браузера очищено')}catch(e){toast(e.message,true)}}
async function refreshBinaries(){try{const s=await window.astra.binaries.status(),items=$$('#binaryStatus strong');items[0].textContent=s.ytDlp.exists?s.ytDlp.version:'Відсутній';items[1].textContent=s.ffmpeg.exists?s.ffmpeg.version:'Відсутній';items[2].textContent=s.ffprobe.exists?s.ffprobe.version:'Відсутній';updateDiagnostics(s)}catch(e){toast(e.message,true)}}
function updateDiagnostics(bin){state.diag=[`App: ${state.app?.name||''} ${state.app?.version||''}`,`Platform: ${state.app?.platform||''} ${state.app?.arch||''}`,`Electron: ${state.app?.electron||''}`,`Node: ${state.app?.node||''}`,`Auth: ${auth().authMode}`,`Browser cookies: ${state.browser?.cookieCount??'not checked'}`,bin?`yt-dlp: ${bin.ytDlp.version||'missing'}`:'',bin?`FFmpeg: ${bin.ffmpeg.version||'missing'}`:''].filter(Boolean).join('\n');$('#diagnosticsBox').textContent=state.diag}
function wire(){$$('.nav-item').forEach(x=>x.addEventListener('click',()=>switchPage(x.dataset.page)));$('#pasteButton').addEventListener('click',async()=>{$('#urlInput').value=await window.astra.system.readClipboard()});$('#analyzeButton').addEventListener('click',analyze);$('#urlInput').addEventListener('keydown',e=>{if(e.key==='Enter')analyze()});$('#downloadButton').addEventListener('click',addDownload);$('#queueList').addEventListener('click',queueAction);$('#outputButton').addEventListener('click',async()=>{const v=await window.astra.dialog.selectOutput($('#outputInput').value);if(v){$('#outputInput').value=v;persist()}});$('#cookiesButton').addEventListener('click',async()=>{const v=await window.astra.dialog.selectCookies();if(v){$('#cookiesInput').value=v;persist()}});$('#cookiesClearButton').addEventListener('click',()=>{$('#cookiesInput').value='';persist()});$$('input[name="authMode"]').forEach(x=>x.addEventListener('change',updateAuthUI));['presetSelect','concurrencySelect','thumbnailCheck','metadataCheck','autoSubtitlesCheck','playlistCheck'].forEach(id=>$('#'+id)?.addEventListener('change',()=>{updateAuthUI();persist()}));$('#subtitlesCheck').addEventListener('change',()=>{$('#subtitleOptions').classList.toggle('hidden',!$('#subtitlesCheck').checked);persist()});$('#subtitleLanguagesInput').addEventListener('change',persist);['openBrowserHeader','openBrowserButton','browserLaunchButton','settingsOpenBrowser'].forEach(id=>$('#'+id)?.addEventListener('click',()=>window.astra.browser.open($('#urlInput').value.trim()||undefined)));['refreshBrowserButton','browserStatusRefresh'].forEach(id=>$('#'+id)?.addEventListener('click',refreshBrowser));['browserClearButton','settingsClearBrowser'].forEach(id=>$('#'+id)?.addEventListener('click',clearBrowser));$('#binaryRefreshButton').addEventListener('click',refreshBinaries);$('#updateYtDlpButton').addEventListener('click',async()=>{const b=$('#updateYtDlpButton');busy(b,true,'Оновлення…');try{const r=await window.astra.binaries.updateYtDlp();toast(`yt-dlp ${r.version}: ${r.changed?'оновлено':'актуальний'}`);await refreshBinaries()}catch(e){toast(e.message,true)}finally{busy(b,false)}});$('#copyDiagnosticsButton').addEventListener('click',async()=>{await window.astra.system.copyText(state.diag);toast('Діагностику скопійовано')});$('#historyList').addEventListener('click',e=>{const b=e.target.closest('[data-path]');if(b?.dataset.path)window.astra.system.openPath(b.dataset.path).catch(err=>toast(err.message,true))});window.astra.downloads.onUpdate(j=>{state.jobs.set(j.id,j);renderQueue();if(j.status==='completed')toast(`Готово: ${j.title}`)});window.astra.browser.onUseUrl(async url=>{$('#urlInput').value=url;const r=$('input[name="authMode"][value="browser"]');r.checked=true;updateAuthUI();switchPage('download');message('Сторінку передано з AstraFetch Browser. Browser session увімкнено.');await refreshBrowser()})}
async function init(){wire();try{const[app,settings,jobs]=await Promise.all([window.astra.app.info(),window.astra.settings.get(),window.astra.downloads.list()]);state.app=app;$('#versionLabel').textContent=`AstraFetch ${app.version}`;applySettings(settings);jobs.forEach(j=>state.jobs.set(j.id,j));renderQueue();await refreshBrowser();updateDiagnostics()}catch(e){message(e.message,true)}}
init();
